config/routes.rb
Rails.application.routes.draw do
  resources :akses_moduls
  resources :moduls
  resources :users
  resources :user_roles
  
  get 'shortcut', to: 'shortcut#index'
  get 'template', to: 'template#index'
  get 'user_roles', to: 'user_roles#index'
  get 'akses_moduls', to: 'akses_moduls#index'
  get 'moduls', to: 'moduls#index'
  get 'users', to: 'users#index'
  root 'dashboard#index'
end

app/models/akses_modul.rb
class AksesModul < ApplicationRecord
    belongs_to :user_role
    belongs_to :modul

    delegate :name_roles, to: :user_role, prefix: true, allow_nil: true 
    delegate :nama_modul, to: :modul, prefix: true, allow_nil: true 
end

app/controllers/akses_moduls_controller.rb
class AksesModulsController < ApplicationController
  before_action :set_akses_modul, only: %i[ show edit update destroy ]

  # GET /akses_moduls or /akses_moduls.json
  def index
    @akses_moduls = AksesModul.all
  end

  # GET /akses_moduls/1 or /akses_moduls/1.json
  def show
  end

  # GET /akses_moduls/new
  def new
    @akses_modul = AksesModul.new
  end

  # GET /akses_moduls/1/edit
  def edit
  end

  # POST /akses_moduls or /akses_moduls.json
  def create
    @akses_modul = AksesModul.new(akses_modul_params)

    respond_to do |format|
      if @akses_modul.save
        format.html { redirect_to akses_modul_url(@akses_modul), notice: "Akses modul was successfully created." }
        format.json { render :show, status: :created, location: @akses_modul }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @akses_modul.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /akses_moduls/1 or /akses_moduls/1.json
  def update
    respond_to do |format|
      if @akses_modul.update(akses_modul_params)
        format.html { redirect_to akses_modul_url(@akses_modul), notice: "Akses modul was successfully updated." }
        format.json { render :show, status: :ok, location: @akses_modul }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @akses_modul.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /akses_moduls/1 or /akses_moduls/1.json
  def destroy
    @akses_modul.destroy

    respond_to do |format|
      format.html { redirect_to akses_moduls_url, notice: "Akses modul was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_akses_modul
      @akses_modul = AksesModul.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def akses_modul_params
      params.require(:akses_modul).permit(:modul_id, :user_role_id)
    end
end

app/helpers/akses_moduls_helper.rb
module AksesModulsHelper
end

app/views/akses_moduls/_akses_modul.html.erb
<tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
    <td class="w-4 p-4">
      <div class="flex items-center">
        <input id="checkbox-table-search-1" type="checkbox"
          class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
        <label for="checkbox-table-search-1" class="sr-only">checkbox</label>
      </div>
    </td>
    <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
      <%= akses_modul.modul_nama_modul %>
    </th>
    <td class="px-6 py-4">
      <%= akses_modul.user_role_name_roles %>
    </td>
    <td class="px-6 py-4">
      Status
    </td>
    
    <td class="px-6 py-4 text-right">
      <a href="/akses_moduls/ <%= akses_modul.id %>/edit" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
    </td>
  </tr>

app/views/akses_moduls/_form.html.erb
<%= form_with(model: akses_modul, class: "contents") do |form| %>
<% if akses_modul.errors.any? %>
<div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
  <h2><%= pluralize(akses_modul.errors.count, "error") %> prohibited this akses_modul from being saved:</h2>

  <ul>
    <% akses_modul.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="shadow-md rounded-lg py-5 px-5 mt-3">
  <div class="flex flex-col mb-4 mt-1">
    <%= form.label :modul_id %>
    <%= form.collection_select :modul_id, Modul.order(:nama_modul),:id,:nama_modul, {include_blank: true}, {class: "rounded-lg mt-2"} %>
  </div>

  <div class="my-5 flex flex-col ">
    <%= form.label :user_role_id %>
    <%# form.text_field :user_role_id, class: " block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full " %>
    <%= form.collection_select :user_role_id, UserRole.order(:name_roles),:id,:name_roles, {include_blank: true}, {class: "rounded-lg mt-2"} %>
  </div>
</div>

<div class="inline">
  <%= form.submit class: "rounded-lg py-3 mt-5 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer sm:flex-row" %>
</div>

<% end %>

app/views/akses_moduls/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-2xl mb-5">Editing Akses Modul</h1>

  <%= render "form", akses_modul: @akses_modul %>

  <%= link_to "Show this akses modul", @akses_modul, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to akses moduls", akses_moduls_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/akses_moduls/index.html.erb
<div class="w-full">
  <% if notice.present? %>
  <p class="py-2 px-3 bg-blueGray-500 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %>
  </p>

  <% end %>
  <div class="flex flex-wrap">
    <div class="w-full rounded-lg md:w-1/2">

      <!---------- Main Content ---------------->
      <div class=" py-4 px-5 rounded-lg shadow-md">
        <div class="flex justify-between items-center mb-1 sm:w-1/2 ">
          <h1 class="font-bold text-xl text-blueGray-700 hover:text-blueGray-500 block"><i
              class="fa-solid fa-box text-2xl mr-2 text-blueGray-400 rounded-full bg-white text-white p-2"></i>Akses Moduls</h1>
          <a class="rounded-lg py-2 px-4 bg-blue-600 text-white block font-medium sm:text-md" href="/akses_moduls/new">Create Akses Moduls New</a>
          <!-- <%= link_to 'New user role', new_user_role_path, class: "rounded-lg py-2 px-4 bg-blue-600 text-white block font-medium" %> -->
        </div>

        <div id="table-container" class="mt-10">
          <div class="w-full items-center ">
            <%= render '/shortcut/search' %>
          </div>

          <div class="py-2">
            <div class="relative border-red-500 rounded-lg overflow-x-auto shadow-md sm:rounded-lg mt-5">
              <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400 ">
                <thead class="text-xs border-b border-gray-500 text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400 ">
                  <tr>
                    <th scope="col" class="p-4">
                      <div class="flex items-center">
                        <input id="checkbox-all-search" type="checkbox"
                          class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                        <label for="checkbox-all-search" class="sr-only">checkbox</label>
                      </div>
                    </th>
                    <th scope="col" class="px-6 py-3">
                      Name Modul
                    </th>
                    <th scope="col" class="px-6 py-3">
                      Nama User Roles
                    </th>
                    <th scope="col" class="px-6 py-3">
                      <span class="sr-only">Edit</span>
                    </th>
                  </tr>
                </thead>
                <tbody class="text-sm divide-y divide-gray-100">
                  <%= render @akses_moduls %>

                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!---------- End ---------------->
    </div>
  </div>
  
</div>

app/views/akses_moduls/new.html.erb
<div
  class="block p-6  bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-2xl">New Akses Modul</h1>

    <%= render "form", akses_modul: @akses_modul %>

    <%= link_to 'Back to akses moduls', akses_moduls_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/akses_moduls/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @akses_modul %>

    <%= link_to 'Edit this akses_modul', edit_akses_modul_path(@akses_modul), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this akses_modul', akses_modul_path(@akses_modul), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to akses_moduls', akses_moduls_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>