config/routes.rb
Rails.application.routes.draw do
  resources :akses_moduls
  resources :moduls
  resources :users
  resources :user_roles
  
  get 'shortcut', to: 'shortcut#index'
  get 'template', to: 'template#index'
  get 'user_roles', to: 'user_roles#index'
  get 'akses_moduls', to: 'akses_moduls#index'
  get 'moduls', to: 'moduls#index'
  get 'users', to: 'users#index'
  root 'dashboard#index'
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :user_role

    delegate :name_roles, to: :user_role, prefix: true, allow_nil: true 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name_user, :user_role_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-6">
    <%= form.label :name_user, class: "mt-10" %>
    <%= form.text_field :name_user, class: "mt-2 block shadow rounded-lg border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5 flex flex-col mt-5">
    <%= form.label :user_role_id %>
    <%# <%= form.text_field :user_roles, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <%= form.collection_select :user_role_id, UserRole.order(:name_roles),:id,:name_roles, {include_blank: true}, {class: "rounded-lg mt-2"} %>
  </div>

  <div class="inline">
    <%= form.submit class: "mt-5 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<tbody>
  <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
    <td class="w-4 p-4">
      <div class="flex items-center">
        <input id="checkbox-table-search-1" type="checkbox"
          class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
        <label for="checkbox-table-search-1" class="sr-only">checkbox</label>
      </div>
    </td>
    <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
      <%= user.name_user %>
    </th>
    <td class="px-6 py-4">
      <%# UserRole.find_by(id: @item.user_role_id).try(:buisness_name) %>
      <%= user.user_role_name_roles %>
    </td>
    <td class="px-6 py-4">
      Status
    </td>
    
    <td class="px-6 py-4 text-right">
      <a href="/users/ <%= user.id %>/edit" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
    </td>
  </tr>


</tbody>

app/views/users/edit.html.erb
<div class="block p-6  bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
  <div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user</h1>

  <%= render "form", user: @user %>

  <!-- <%= link_to "Show this user", @user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %> -->
  <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

</div>

app/views/users/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class=" py-4 px-5 rounded-lg shadow-md">
    <div class="flex justify-between items-center mb-1">
      <h1 class="font-bold text-xl text-blueGray-700 hover:text-blueGray-500 block "><i
              class="fa-solid fa-user-secret text-2xl mr-2 text-blueGray-400 rounded-full bg-white text-white p-2"></i>User
            </h1>
          <a class="rounded-lg py-2 px-4 bg-blue-600 text-white block font-medium" href="/users/new">Create
            User</a>
    </div>

     <div id="table-container" class="mt-10">
      <!-------------- Search -------------->
      <div class="w-full items-center">
        <%= render '/shortcut/search' %>
      </div>
      <!-------------- End Search -------------->

      <div class="py-2">
        <div class="relative border-red-500 rounded-lg overflow-x-auto shadow-md sm:rounded-lg mt-5">
          <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400 ">
            <thead class="text-xs border-b border-gray-500 text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                  <tr>
                    <th scope="col" class="p-4">
                      <div class="flex items-center">
                        <input id="checkbox-all-search" type="checkbox"
                          class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                        <label for="checkbox-all-search" class="sr-only">checkbox</label>
                      </div>
                    </th>
                    <th scope="col" class="px-6 py-3">
                      Name User
                    </th>
                    <th scope="col" class="px-6 py-3">
                      User Roles
                    </th>
                    <th scope="col" class="px-6 py-3">
                      <span class="sr-only">Edit</span>
                    </th>
                  </tr>
                </thead>
                <tbody class="text-sm divide-y divide-gray-100">
                  <%= render @users %>
                </tbody>
          </table>
        </div>
      </div>
     </div>
  </div>

  <!-- <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Users</h1>
    <%= link_to 'New user', new_user_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div> -->


</div>

app/views/users/new.html.erb
<div class="block p-6  bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-2xl">New user </h1>

    <%= render "form", user: @user %>

    <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user %>

    <%= link_to 'Edit this user', edit_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this user', user_path(@user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>