config/routes.rb
Rails.application.routes.draw do
  resources :akses_moduls
  resources :moduls
  resources :users
  resources :user_roles
  
  get 'shortcut', to: 'shortcut#index'
  get 'template', to: 'template#index'
  get 'user_roles', to: 'user_roles#index'
  get 'akses_moduls', to: 'akses_moduls#index'
  get 'moduls', to: 'moduls#index'
  get 'users', to: 'users#index'
  root 'dashboard#index'
end

app/models/user_role.rb
class UserRole < ApplicationRecord
    has_many :akses_moduls
    has_many :user
end

app/controllers/user_roles_controller.rb
class UserRolesController < ApplicationController
  before_action :set_user_role, only: %i[ show edit update destroy ]

  # GET /user_role or /user_role.json
  def index
    @user_role = UserRole.all 
  end

  # GET /user_role/1 or /user_role/1.json
  def show
    # @user_role = UserRole.find(user_role_params[:id])
  end

  # GET /user_role/new
  def new
    @user_role = UserRole.new
  end

  # GET /user_role/1/edit
  def edit
  end

  # POST /user_role or /user_role.json
  def create
    @user_role = UserRole.new(user_role_params)

    respond_to do |format|
      if @user_role.save
        format.html { redirect_to user_role_url(@user_role), notice: "User role was successfully created." }
        format.json { render :show, status: :created, location: @user_role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_role/1 or /user_role/1.json
  def update
    respond_to do |format|
      if @user_role.update(user_role_params)
        format.html { redirect_to user_role_url(@user_role), notice: "User role was successfully updated." }
        format.json { render :show, status: :ok, location: @user_role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_role/1 or /user_role/1.json
  def destroy
    @user_role.destroy

    respond_to do |format|
      format.html { redirect_to user_role_url, notice: "User role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_role
      @user_role = UserRole.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_role_params
      params.require(:user_role).permit(:name_roles, :roles_level)
    end
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/user_roles/_form.html.erb
  <%= form_with(model: user_role, class: "contents") do |form| %>

  <% if user_role.errors.any? %>
  <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
    <h2><%= pluralize(user_role.errors.count, "error") %> prohibited this user_role from being saved:</h2>

    <ul>
      <% user_role.errors.each do |error| %>
      <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>


  <div class="my-5">
    <%= form.label :name_roles %>
    <%= form.text_field :name_roles, class: "block shadow rounded-lg border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5 mt-5">
    <%= form.label :roles_level %>
    <%= form.text_field :roles_level, class: "block shadow rounded-lg border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline ">
    <input href="/user_roles" type="submit" name="commit" value="Update User role"
      class="mt-5 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"
      data-disable-with="Update User role">
  </div>

  <% end %>

app/views/user_roles/_user_role.html.erb
<tbody>

  <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
    <td class="w-4 p-4">
      <div class="flex items-center">
        <input id="checkbox-table-search-1" type="checkbox"
          class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
        <label for="checkbox-table-search-1" class="sr-only">checkbox</label>
      </div>
    </td>
    <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
      <%= user_role.name_roles %>
    </th>
    <td class="px-6 py-4">
      <%= user_role.roles_level %>
    </td>
    <td class="px-6 py-4">
      Status
    </td>
    
    <td class="px-6 py-4 text-right">
      <a href="/user_roles/ <%= user_role.id %>/edit" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
    </td>
  </tr>


</tbody>

app/views/user_roles/edit.html.erb
<div class="block p-6  bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
 
    <h1 class="font-bold text-xl text-blueGray-700 hover:text-blueGray-500 block mb-5">Editing user role</h1>
    <%= render "form", user_role: @user_role %>
    <%= link_to "Back to user roles", user_roles_path, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium ml-3" %>
  
</div>

app/views/user_roles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
  <p class="py-2 px-3 bg-blueGray-500 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %>
  </p>

  <% end %>
  <div class="flex flex-wrap">
    <div class="w-full rounded-lg md:w-1/2">

      <!---------- Main Content ---------------->
      <div class=" py-4 px-5 rounded-lg shadow-md">
        <div class="flex justify-between items-center mb-1">
          <h1 class="font-bold text-xl text-blueGray-700 hover:text-blueGray-500 block "><i
              class="fa-solid fa-box text-2xl mr-2 text-blueGray-400 rounded-full bg-white text-white p-2"></i>User
            roles</h1>
          <a class="rounded-lg py-2 px-4 bg-blue-600 text-white block font-medium" href="/user_roles/new">Create
            User Roles</a>
          <!-- <%= link_to 'New user role', new_user_role_path, class: "rounded-lg py-2 px-4 bg-blue-600 text-white block font-medium" %> -->
        </div>

        <div id="table-container" class="mt-10">
          <div class="w-full items-center ">
            <%= render '/shortcut/search' %>
          </div>

          <div class="py-2">
            <div class="relative border-red-500 rounded-lg overflow-x-auto shadow-md sm:rounded-lg mt-5">
              <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400 ">
                <thead class="text-xs border-b border-gray-500 text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400 ">
                  <tr>
                    <th scope="col" class="p-4">
                      <div class="flex items-center">
                        <input id="checkbox-all-search" type="checkbox"
                          class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                        <label for="checkbox-all-search" class="sr-only">checkbox</label>
                      </div>
                    </th>
                    <th scope="col" class="px-6 py-3">
                      Name Roles
                    </th>
                    <th scope="col" class="px-6 py-3">
                      Level Roles
                    </th>
                    <th scope="col" class="px-6 py-3">
                      <span class="sr-only">Edit</span>
                    </th>
                  </tr>
                </thead>
                <tbody class="text-sm divide-y divide-gray-100">
                  <%= render @user_role %>

                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!---------- End ---------------->
    </div>
  </div>
  <!--<div class="flex justify-between items-center mb-4">
    <h1 class="font-bold text-xl">User roles</h1>
    <%= link_to 'New user role', new_user_role_path, class: "rounded-lg py-2 px-4 bg-blue-600 text-white block font-medium" %>
  </div>

  <% <div id="user_role" class="min-w-full">
    <div class="shadow-xl p-5 rounded-lg bg-white">
      <table class="w-full text-sm text-left text-gray-500 ">
        <thead class="text-xs text-gray-700 uppercase bg-white">
          <tr class="border-b">
            <th scope="col" class="">Status </th>
            <th scope="col" class="px-6 py-3">Nama Roles</th>
            <th scope="col" class="px-6 py-3">Roles level</th>
          </tr>
        </thead>

        
      </table>
    </div>
  </div> -->
</div>

app/views/user_roles/new.html.erb
<div class="block p-6  bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
  <div class="mb-5">
    <h1 class="font-bold text-xl text-blueGray-700 hover:text-blueGray-500 block ">New user role</h1>
  </div>

  <%= render "form", user_role: @user_role %>
  <%= link_to 'Back to user roles', user_roles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <!-- <button class="rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer">Create User Roles</button> -->
</div>

app/views/user_roles/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render  @user_role %>

    <%= link_to 'Submit Edit', edit_user_role_path(@user_role), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this user_role', user_role_path(@user_role), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to user_roles', user_roles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>