config/routes.rb
Rails.application.routes.draw do
  resources :akses_moduls
  resources :moduls
  resources :users
  resources :user_roles
  
  get 'shortcut', to: 'shortcut#index'
  get 'template', to: 'template#index'
  get 'user_roles', to: 'user_roles#index'
  get 'akses_moduls', to: 'akses_moduls#index'
  get 'moduls', to: 'moduls#index'
  get 'users', to: 'users#index'
  root 'dashboard#index'
end

app/models/modul.rb
class Modul < ApplicationRecord
    has_many :akses_moduls
end

app/controllers/moduls_controller.rb
class ModulsController < ApplicationController
  before_action :set_modul, only: %i[ show edit update destroy ]

  # GET /moduls or /moduls.json
  def index
    @moduls = Modul.all
  end

  # GET /moduls/1 or /moduls/1.json
  def show
  end

  # GET /moduls/new
  def new
    @modul = Modul.new
  end

  # GET /moduls/1/edit
  def edit
  end

  # POST /moduls or /moduls.json
  def create
    @modul = Modul.new(modul_params)

    respond_to do |format|
      if @modul.save
        format.html { redirect_to modul_url(@modul), notice: "Modul was successfully created." }
        format.json { render :show, status: :created, location: @modul }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @modul.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moduls/1 or /moduls/1.json
  def update
    respond_to do |format|
      if @modul.update(modul_params)
        format.html { redirect_to modul_url(@modul), notice: "Modul was successfully updated." }
        format.json { render :show, status: :ok, location: @modul }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @modul.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moduls/1 or /moduls/1.json
  def destroy
    @modul.destroy

    respond_to do |format|
      format.html { redirect_to moduls_url, notice: "Modul was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modul
      @modul = Modul.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def modul_params
      params.require(:modul).permit(:nama_modul, :status)
    end
end

app/helpers/moduls_helper.rb
module ModulsHelper
end

app/views/moduls/_form.html.erb
<%= form_with(model: modul, class: "contents") do |form| %>
  <% if modul.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(modul.errors.count, "error") %> prohibited this modul from being saved:</h2>

      <ul>
        <% modul.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5 mt-3 ">
    <%= form.label :nama_modul %>
    <%= form.text_field :nama_modul, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5 mt-3">
    <%= form.label :status %>
    <%= form.text_field :status, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/moduls/_modul.html.erb
    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
    <td class="w-4 p-4">
      <div class="flex items-center">
        <input id="checkbox-table-search-1" type="checkbox"
          class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
        <label for="checkbox-table-search-1" class="sr-only">checkbox</label>
      </div>
    </td>
    <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
      <%= modul.nama_modul %>
    </th>
    <td class="px-6 py-4">
      <%= modul.status %>
    </td>
    <td class="px-6 py-4">
      Status
    </td>
    
    <td class="px-6 py-4 text-right">
      <a href="/moduls/ <%= modul.id %>/edit" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
    </td>
  </tr>
</div>

app/views/moduls/edit.html.erb
<div class="block p-6  bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-2xl mb-5">Editing modul</h1>

    <%= render "form", modul: @modul %>

    <%= link_to "Show this modul", @modul, class: " mt-2 ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to moduls", moduls_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/moduls/index.html.erb
<div class="w-full">
  <% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class=" py-4 px-5 rounded-lg shadow-md">
    <div class="flex justify-between items-center mb-1">
      <h1 class="font-bold text-xl text-blueGray-700 hover:text-blueGray-500 block "><i
          class="fa-solid fa-user-secret text-2xl mr-2 text-blueGray-400 rounded-full bg-white text-white p-2"></i>Moduls
      </h1>
      <a class="rounded-lg py-2 px-4 bg-blue-600 text-white block font-medium" href="/moduls/new">Create
        Modul</a>
    </div>

    <div id="table-container" class="mt-10">
       <!-------------- Search -------------->
      <div class="w-full items-center">
        <%= render '/shortcut/search' %>
      </div>
      <!-------------- End Search -------------->

      <div class="py-2">
        <div class="relative border-red-500 rounded-lg overflow-x-auto shadow-md sm:rounded-lg mt-5">
          <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400 ">
            <thead class="text-xs border-b border-gray-500 text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
              <tr>
                <th scope="col" class="p-4">
                  <div class="flex items-center">
                    <input id="checkbox-all-search" type="checkbox"
                      class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                    <label for="checkbox-all-search" class="sr-only">checkbox</label>
                  </div>
                </th>
                <th scope="col" class="px-6 py-3">
                  Name User
                </th>
                <th scope="col" class="px-6 py-3">
                  User Roles
                </th>
                <th scope="col" class="px-6 py-3">
                  <span class="sr-only">Edit</span>
                </th>
              </tr>
            </thead>
            <tbody class="text-sm divide-y divide-gray-100">
              <%= render @moduls %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/moduls/new.html.erb
<div
  class="block p-6  bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-2xl">New modul</h1>

    <%= render "form", modul: @modul %>

    <%= link_to 'Back to moduls', moduls_path, class: "mt-5 ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/moduls/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @modul %>

    <%= link_to 'Edit this modul', edit_modul_path(@modul), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this modul', modul_path(@modul), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to moduls', moduls_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>